# -*- coding: utf-8 -*-
"""Multi_dataframe_Agents_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PeuRBSI6-sXByfXRrssUji8wPxDUxv8n

#**In LangChain, the Agent can access many dataframes at once**

#**01: Install All the Required Packages**
"""

!pip install langchain langchain_experimental
!pip install watermark
!pip install openai

"""#**02: Import All The Required Libraries**"""

import os
import warnings
warnings.filterwarnings("ignore")

from langchain_experimental.agents.agent_toolkits import create_pandas_dataframe_agent
from langchain.llms import OpenAI

import pandas as pd

"""#**03: Setup the Environment**

"""

os.environ['OPENAI_API_KEY'] = ""

"""#**04:Data**"""

url = "https://raw.githubusercontent.com/Premalatha-success/Datasets/refs/heads/main/titanic-training-data.csv"
df=pd.read_csv(url)
print(df.shape)
df.head()

"""#**05: Single DataFrame Example**

#**Agent can interact with Single DataFrame**
"""

llm=OpenAI()

agent=create_pandas_dataframe_agent(llm, df, verbose=True, allow_dangerous_code=True, handle_parsing_errors=True)

agent.run("How many rows are there")

agent.run("How many people have more than 23 age")

"""#**06: Multi DataFrame Example**

#**Agent can also interact with Multiple DataFrames passed in a list**
"""

df.info()

df1=df.copy()

df1

df1["age"] = df1["Age"].fillna(df1["Age"].mean())

agent=create_pandas_dataframe_agent(llm, [df, df1], verbose=True,allow_dangerous_code=True)

agent.run("How many rows in the age column are different")

df2=df1.copy()

df2["Age_Multiplied"]=df1["Age"] * 2

df2.head()

agent=create_pandas_dataframe_agent(llm, [df,df1, df2], verbose=True, allow_dangerous_code=True)

agent.run("Are the number of columns same in all the dataframe")

agent.run("What is the mean age?")

