# -*- coding: utf-8 -*-
"""Simple_agent_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ltJK0WV5kAseTaa4MCiRqulV53zYxop8
"""

pip install langchain langchain-community transformers accelerate

from langchain.agents import initialize_agent, Tool
from langchain.agents.agent_types import AgentType
from langchain.memory import ConversationBufferMemory
from langchain.chat_models import ChatOpenAI
import os

os.environ["OPENAI_API_KEY"] =

llm = ChatOpenAI(temperature=0)

def simple_calc(input: str) -> str:
    return str(eval(input))

tools = [
    Tool(
        name="Calculator",
        func=simple_calc,
        description="Useful for basic math like addition, multiplication, etc."
    )
]

memory = ConversationBufferMemory(memory_key="chat_history")

agent = initialize_agent(
    tools=tools,
    llm=llm,
    agent=AgentType.CONVERSATIONAL_REACT_DESCRIPTION,
    verbose=True,
    memory=memory
)

response1 = agent.run("What is 24 * 17?")
print("Agent:", response1)

response2 = agent.run("Now add 100 to it.")
print("Agent:", response2)

response3 = agent.run("Repeat what we discussed so far.")
print("Agent:", response3)

!pip install duckduckgo-search

from langchain_community.tools import DuckDuckGoSearchRun
# File Reader Tool
def file_reader_tool(query: str) -> str:
    try:
        with open("/content/training_data.txt", "r") as file:
            content = file.read()
            return content[:1000]
    except Exception as e:
        return f"Error reading file: {str(e)}"

# Web Search Tool
search = DuckDuckGoSearchRun()

# Tools List
tools = [

    Tool(
        name="FileReader",
        func=file_reader_tool,
        description="Reads content from a local text file called sample.txt."
    ),
    Tool(
        name="WebSearch",
        func=search.run,
        description="Useful for answering questions about current events or facts using the internet."
    )
]

# Agent
agent = initialize_agent(
    tools=tools,
    llm=llm,
    agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
    verbose=True
)

# Example Queries

print(agent.run("Read the file and tell me its content."))

print(agent.run("Who is the current CEO of OpenAI?"))

print(agent.run("Who is the current CEO of OpenAI?Use websearch"))

print(agent.run("Who is Premalatha,Corporate Trainer?"))

