# -*- coding: utf-8 -*-
"""weather_agent_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g7-FOqaA8Go6Pq9epGGovGSQdfMjLCy6
"""

!pip install -q smolagents



!pip install markdownify duckduckgo-search spaces gradio-tools langchain langchain-community langchain-huggingface faiss-cpu --upgrade -q

from huggingface_hub import notebook_login

notebook_login()

from smolagents import InferenceClientModel

model_id = "Qwen/Qwen2.5-72B-Instruct"
model = InferenceClientModel(model_id)

from smolagents import CodeAgent, ToolCallingAgent, DuckDuckGoSearchTool, VisitWebpageTool

web_agent = ToolCallingAgent(tools=[DuckDuckGoSearchTool(), VisitWebpageTool()], model=model)

# Now, use web_agent directly
query = "What's the weather like in Chennai today?"

result = web_agent.run(query)
print(result)

from IPython.display import Image, display

display(Image(filename=result))

